### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by tyleransom** [garthtarr/sydney_xaringan#5]
I wanted to first say thanks for putting this together. It's been really helpful for me to figure out `xaringan`.

I have a couple of questions that I couldn't find answers to in your example slides. I suspect you could answer these off the top of your head, which is why I'm bothering you about them. Thank you in advance!

1. Do you know why I can't change the color of text in a nested bulleted list? e.g.

```
# Slide title

- point 1

    - .brand-red[Sydney master brand red] text

---
```

does not render the color in the nested bullet, but if I want to change the color in the first bullet, I can do it fine:

```
# Slide title

- .brand-red[point 1]

    - some text

---
```

Have you ever encountered this behavior? Otherwise it may be an issue with my CSS.

2. Do you happen to know why math inside of parentheses doesn't render? Here's an example The code I have that won't work is

```
# Some variables

- $(x)$

- ($x$)
```

The first one renders but the second one doesn't. Coming from LaTeX, this is confusing, since both would render as expected in LaTeX.

**Comment by garthtarr** [comment]
I think these are more fundamental xaringan questions, you'd probably get better answers on [stackoverflow](https://stackoverflow.com/questions/tagged/xaringan)!

I've encountered 1. before and I have no idea why it happens in deeply nested lists but is OK in the first nesting. 

For 2. I think you need a white space around the $(x)$ or at least at the start of the $(x)$ so that it is correctly identified as math mode.

**Comment by tyleransom** [comment]
Thanks for your time! I'll check out SO
